compile1:
		gcc Q1_part1.c -o output1.out
# 	Compile your code for first part here

run1: compile1 
	./output1.out
# 	 Execute part 1 here

compile2:
		gcc Q1_part2.c -lpthread -o output2.out
# 	Compile your code for second part here

run2: compile2
	./output2.out
#	Execute part 2 here

